### ISSUE TITLE
Can I run the experiment without cloublab?

### ISSUE THREAD

**Issue by flash6666** [alex1230608/contra#4]
Can I  run the mininet emulation with Contra not using cloudlab?
I want to run the experiment only in the mininet . what should i do or how to modify?

**Comment by alex1230608** [comment]
Yes, but it needs some effort to change the codes. The reason we used cloudlab is to have multiple machines with enough capability to support heavier traffic workload with minimal performance degradation. If the measurement accuracy on performance is secondary for your setup, you can simply run Contra on a single machine.

To set up the environment, you can just download [the packages.sh file ](https://github.com/alex1230608/contra/blob/master/P4-mininet-cluster/packages.sh) on your machine and skip to step 4 in the [readme](https://github.com/alex1230608/contra#environment-setup).

Note that you may want to run packages.sh one line at a time manually instead of the whole script at once since many compatibility issues may happen and need careful check manually. Sorry for not having a better script for this setup.

The steps to install the Contra compiler and compile Contra policies are similar to those described in the Readme. However, before you run the workload, you will have to modify the p4app.json to configure it to use the same machine. For example, in [this example](https://github.com/alex1230608/contra/tree/master/P4-mininet-cluster/fattree45_MU_FTO50_pkttags/app), the p4app.json is originally configured to have 19 machines (only 15 machines are really used though). The server index starts from 0, so to make all switches and hosts running on local machine, you can simply 
1. Change all `"server": "XX"` to `"server": "0"` in [these lines](https://github.com/alex1230608/contra/blob/master/P4-mininet-cluster/fattree45_MU_FTO50_pkttags/app/p4app.json#L12-L294)
2. Change [this line](https://github.com/alex1230608/contra/blob/master/P4-mininet-cluster/fattree45_MU_FTO50_pkttags/app/p4app.json#L342) to `"servers": ["localhost"],`

**Comment by flash6666** [comment]
Change all "server": "XX" to "server": "0" in these lines
Change this line to "servers": ["localhost"]  the change is like the picture ?
![1648217350(1)](https://user-images.githubusercontent.com/67527632/160136697-d3e4044d-2fbb-43be-91bd-4c4ca3bdc094.png) 

when i am not specify the --topotype ,the Generated p4app.json is  same as the changed Two modifications mentioned above.
Now, i can run the mininet but it is unconnected  between hosts ,and the mininet is lag.

**Comment by alex1230608** [comment]
Re using topotype: If I remember it correctly, you are probably right: skipping topotype flag may actually generate codes for localhost testing. However, it has been a while since the project was proposed. I might be wrong.

Re errors and warnings: The errors on RemoteLink are fine. Based on my experience, they won't affect the experiments. The warnings from p4c should also be fine.

Re other potential problems: The mininet will become very slow if there are too many switches to emulate and your machine does not have enough capacity (memory or computation resource) to hold them. You can start with simpler examples like 25-switch fattree or abilene, or even smaller like a 4-switch diamond topology. This may also be the root cause of the connectivity problem because the switches react to the traffic too slowly.

**Comment by flash6666** [comment]
Now, I run the example that is abilene with the command (hula --policy examples/util/util.hula --topo realDataTest/xmlData/Abilene.xml.edge --topotype ABILENE)  
it is  11-switchs but it is still unconnected
I have some questions:
Is it necessary to add ARP and ip route?
![image](https://user-images.githubusercontent.com/67527632/160552559-3bba785d-cc8d-4a07-b230-640029071deb.png)
What's the use of ifconfigstats.py sX- 90-1-DCTCP?

![image](https://user-images.githubusercontent.com/67527632/160553105-10a41cbe-639c-47a8-ad81-2565f3c788e4.png)
![image](https://user-images.githubusercontent.com/67527632/160554332-0269988e-81ef-4256-b045-3f199818c024.png)

i want to generate diamond topology p4 program using the command as Figure above but it is false.

**Comment by flash6666** [comment]
"NUM_END_HOSTS": "2" in p4appjson is use to?
I cannot use client.py to send traffic.  Is the connection between hosts related to sendProbeLoop.py?
when i run the sendProbeLoop.py, the mininet is slowly.
Can I contact you by email？

**Comment by alex1230608** [comment]
(1) When mininet is constructing the topology, it needs this parameter to determine how many extra end hosts it should connect to each ToR switch (for fattree topologies) or edge switch (for arbitrary topologies). By “extra”, I mean in addition to a single control end host which serves as the controller for each switch. There is one controller end host per switch and the id is one-to-one mapping (e.g., s1’s controller end host is h1). When NUM_END_HOST is 2, it means in addition to the controller end hosts, we attach 2 more end hosts to each ToR switch / edge switches. In our setup, all switches in the arbitrary topologies are considered edge switches because they are like the routers in the internet. Note that the Contra compiler automatically creates the topology accordingly along with this parameter, so changing p4app.json file requires changing the topology too. Please only change it if you understand the mininet codes here: https://github.com/alex1230608/contra/tree/master/P4-mininet-cluster/utils

10.0.1.0/24, … 10.0.11.0/24 are the prefixes for end hosts connected to ToR/edge switch s1, …, s11.
For controller end hosts, the IP addresses will be 10.0.1.10, …, 10.0.11.10. For the extra end hosts, the IP addresses will be 10.0.1.21, 10.0.1.22, …, 10.0.11.21, 10.0.11.22 if NUM_END_HOSTS = 2.

&&& are the way to write the ternary keys in simple_switch’s runtime_CLI. 6&&&0xFF means matching on value 6 with mask 0xFF.

(2) As the comment mentions, we do not expect any traffic to reach that else-branch. I think we should have removed that useless table to avoid confusion. Please ignore it for now.

(3) Yes, Abilene_SPAIN is the SPAIN as described in this paper: SPAIN: COTS Data-Center Ethernet for Multipathing over Arbitrary Topologies
If I remember it correctly, Abilene_SPAIN_SP is probably doing similar things except that it only does load balancing across the shortest paths between any two end points. Note there can be multiple shortest paths with the same length between two points on a topology.

(4) Yes, we used Client.py to send traffic, and yes the FCT is from the output of Client.py. Note that the connection we used is TCP, so there will be ACKs from the receiver and it finishes send loop only after all messages are acked by the receiver. Also, even if the measurement does not cover the last few packets, it won’t change much on the result of measurement.

To calculate the average FCT, you can simply collect all the logs (the output of the Client.py) after running run.sh with the p4app.json which holds the right commands. See here to find the commands in p4app.json and you will know where to find the logs: https://github.com/alex1230608/contra/blob/master/P4-mininet-cluster/fattree45_MU_FTO50_pkttags/app/p4app.json#L10353-L10379

We thank you for asking these questions here, which may help other people who have similar questions. You can continue to use Github to ask questions, which reach me via email automatically already. But, if you prefer a private channel, you can contact me by email directly if you want.

**Comment by flash6666** [comment]
Thank you so much.

**Comment by l-x007** [comment]
> Can I run the mininet emulation with Contra not using cloudlab? I want to run the experiment only in the mininet . what should i do or how to modify?

May I ask if you have used cloudlab to run, I am also working on this project recently, if you use cloudlab, I would like to know how you applied for a cloudlab account.I can't apply for a cloudlab account.

**Comment by flash6666** [comment]
> > Can I run the mininet emulation with Contra not using cloudlab? I want to run the experiment only in the mininet . what should i do or how to modify?
> 
> May I ask if you have used cloudlab to run, I am also working on this project recently, if you use cloudlab, I would like to know how you applied for a cloudlab account.I can't apply for a cloudlab account.
I also can't apply for a cloudlab account.  Maybe you can try to use ns-3 to do it.

**Comment by l-x007** [comment]
> > I also can't apply for a cloudlab account.  Maybe you can try to use ns-3 to do it。
Do I need to modify the code if I use ns-3? If necessary, how to modify it.

**Comment by l-x007** [comment]
> > > Can I run the mininet emulation with Contra not using cloudlab? I want to run the experiment only in the mininet . what should i do or how to modify?
> > 
> > 
> > May I ask if you have used cloudlab to run, I am also working on this project recently, if you use cloudlab, I would like to know how you applied for a cloudlab account.I can't apply for a cloudlab account.
> > I also can't apply for a cloudlab account.  Maybe you can try to use ns-3 to do it.

Do I need to modify the code if I use ns-3? If necessary, how to modify it.

**Comment by alex1230608** [comment]
> Can the probe only be sent through h1~h11? When I send through other hosts，I can't send packets by client/serve.py I have measured some data (mininet environment), but the effect is not very good(contra-mu fct is bigger than sp). I think the possible reason is that all hosts are running on one host, resulting in too slow response of the switch to traffic or too great impact caused by probe sending In this environment. Is it reasonable for me to think so? Maybe the test flow is too small, resulting in poor results? If I want to debug to make the effect better, what parameters are suggested to be modified？ Thank you so much.

Yes, the one-host setup may cause problems on performance measurement. The more traffic you have in the mininet, the more host computation resource mininet used. Since you only use a single host, it is very likely the computation resource is out. You can check the CPU usage with command like `top` to verify this.

To avoid this, you can scale down the experiments by changing the bandwidth of the links. [Here](https://github.com/alex1230608/contra/blob/master/P4-mininet-cluster/utils/mininet/apptopo.py#L42) is the constant controlling the link bandwidth.

**Comment by alex1230608** [comment]
> > Can I run the mininet emulation with Contra not using cloudlab? I want to run the experiment only in the mininet . what should i do or how to modify?
> 
> May I ask if you have used cloudlab to run, I am also working on this project recently, if you use cloudlab, I would like to know how you applied for a cloudlab account.I can't apply for a cloudlab account.

I think you should contact CloudLab about the application issue. Please note that mininet cluster feature may also work on other server clusters you have control on (e.g., sudo access, ssh to each other, etc.).

**Comment by alex1230608** [comment]
> > > > Can I run the mininet emulation with Contra not using cloudlab? I want to run the experiment only in the mininet . what should i do or how to modify?
> > > 
> > > 
> > > May I ask if you have used cloudlab to run, I am also working on this project recently, if you use cloudlab, I would like to know how you applied for a cloudlab account.I can't apply for a cloudlab account.
> > > I also can't apply for a cloudlab account.  Maybe you can try to use ns-3 to do it.
> 
> Do I need to modify the code if I use ns-3? If necessary, how to modify it.

ns-3 does not support bmv2 simple switch directly last time I checked. Although with extra effort, it is possible.

**Comment by flash6666** [comment]
I want to ask how is the path utilization calculated?  I don't quite understand according to code

**Comment by flash6666** [comment]
> I want to ask how is the path utilization calculated? I don't quite understand according to code
